### ISSUE TITLE
Add support for ApplePi DAC

### ISSUE THREAD

**Issue by orchardaudio** [ralph-irving/tcz-jivelite#4]
Hello,

Please add ApplePi DAC support to picoreplayer.

It has already been added to raspian per this request here:
https://github.com/raspberrypi/linux/issues/2302

Here is the overlay information.
[ApplePi-DAC_dtbo_dts.zip](https://github.com/ralph-irving/tcz-jivelite/files/1910413/ApplePi-DAC_dtbo_dts.zip)

Thanks;
Leo

**Comment by ralph-irving** [comment]
Support has already been added to picoreplayer 3.5.0.

**Comment by orchardaudio** [comment]
Thank you.
