### ISSUE TITLE
Does not honour ts_calibrate with HDMI touchscreen (Y Inverted)

### ISSUE THREAD

**Issue by jamesarbrown** [ralph-irving/tcz-jivelite#5]
I have a Kedei/waveshare ADS7846 + HDMI display which in config text has 

tc@piCorePlayer:~$ sudo TSLIB_TSDEVICE=/dev/input/event0 /usr/local/bin/ts_calibrate
xres = 480, yres = 320
Took 6 samples...
Top left : X =  265 Y = 3728
Took 4 samples...
Top right : X = 3824 Y = 3844
Took 5 samples...
Bot right : X = 3869 Y =  271
Took 6 samples...
Bot left : X =  260 Y =  254
Took 3 samples...
Center : X = 1977 Y = 1986
-23.010315 0.128281 0.000717
328.396729 0.001586 -0.085109
Calibration constants: -1508004 8406 47 21521808 103 -5577 65536

Which all works when I run tc_test.

So when Jivelive fires up and gives language selection, the Y is inverted. X is fine.

I also tried swapping swapxy=0 and re running the calibrate.

The ribbon connector is top right and the jivelite orientation matches the "boot" orientation.

For info grabbed from the waveshare site I also added this lot, which was mainly as I was dropping the resolution to 480

hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 480 320 60 6 0 0 0
hdmi_drive=2

I also tried swapping from HDMI display = 180 to 0, as it seems that parameter wont make any difference and maybe thought jivelite was thinking display was upside down

**Comment by ralph-irving** [comment]
I don't have any waveshare/hdmi screens to try and reproduce your issue.

Perhaps a slimdevices forum member can help.  I'd suggest reading through the forum thread below

https://forums.slimdevices.com/showthread.php?107366-picoreplayer-3-11-waveshare-3-5-TFT-jivelite-Raspberry-Pi-2B

**Comment by jamesarbrown** [comment]
Thanks Ralph. It is something to do with that PCP "outofbox" is not
SDL_MOUSEDRV=TSLIB

So in essence Jivelite "outofbox" on Pcp does not use TSLIB and is perhaps using system event handling?

This is what I think and am working on it now.

**Comment by jamesarbrown** [comment]
From various tests I have established, that Jivelite uses SDL, however SDL can also make use of TSLib, but neither way resulted in a solution to fix my issue.

Test A - Via SDL No Issues, but no way to reverse axes
1) Jivelite uses SDL and accesses the event handler by default and utilises in my case event0, The device used is set by
export SDL_MOUSEDEV=/dev/input/event0

Test B - SDL using piggy back to TSLIB, but broken SDL/TSLib
1) It seems Jivelite can use TSLIB, if we 
export SDL_MOUSEDEV=/dev/input/event0
export SDL_MOUSEDRV=TSLIB
and then run jivelite

2) ts_test and ts_calibrate are done and work

3) The cursor will now work in correct directions, BUT, it now seems that at 0,0 is fine, **but as we run down to the bottom right of screen the cusor is at 50% position**, pretty much that is does not go far beyond the screen centre.

_A similar problem is reported here that TSLIB > SDL is unreliable and seems a similar fault.
https://www.impulseadventure.com/elec/rpi-install-tslib.html_


**So need to figure how to get an updated TSLIB 1.19 from 1,16..... and diagnose further**

**Comment by jamesarbrown** [comment]
Hi Ralphy,

The issue is somewhere in Jive...... 

ts_test and ts_calibrate, honour the current resolution.

Jive however uses the TSLib and pointer cal accordingly, but scales that with the resolution of the skin. 

So in my case it was using a 480x320 pointer cal, on a 640x480 resolution skin.

I do not know the ins and outs of Jivelite, but was of the view if ts_calibrate was right, Jive should use the same mechanism? Maybe jive does usually use the SDL framebuffer passed info for RPI, but under HDMI it is not seeing this? #beyondmyknowledge

I guess this can be marked closed, or better still flagged for an improvement?
