### ISSUE TITLE
Use Jivelite for UV meters on seperate displays

### ISSUE THREAD

**Issue by BGSputnik** [ralph-irving/tcz-jivelite#6]
Hi I am planning to use Jivelite together with PicoCorePlayer on an Raspberry Pi 3B+. To make the front plate looked balanced I would very much prefer to have the left and right VU meter (which I want to realize with Jivelite) on separate displays and let PicoCorePlayer handle a center display for music artwork. Has anybody an idea how to modify Jivelite in a way to feed one channel music into it and to display the VU meter on a separate display ?

**Comment by ralph-irving** [comment]
I made a suggestion on the slimdevices forum how this might be accomplished.
